// src/app/layout.js

import ClientLayout from "./client-layout";
import ClientQueryProvider from "./ClientQueryProvider";
import "../styles/global.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "World Speech AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo-Vector.png" type="image/png" />
      <body>
        <NextTopLoader />
        <ClientQueryProvider>
          <ClientLayout>{children}</ClientLayout>
        </ClientQueryProvider>
      </body>
    </html>
  );
}
