// src/app/layout.js

import ClientQueryProvider from "./hooks/ClientQueryProvider";
import "../styles/global.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "World Speech AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo-Vector.png" type="image/png" />
      <body>
        <NextTopLoader showSpinner={false} />
        <ClientQueryProvider>{children}</ClientQueryProvider>
      </body>
    </html>
  );
}
